// This file is required by the index.html file and will
// be executed in the renderer process for that window or web browser.
// All of the Node.js APIs are available in this process.

import React from 'react'
import ReactDOM from 'react-dom'
import AppConfig from '../AppConfig'
import {Router, HashRouter} from 'react-router-dom'

// ### Custom hashHistory is generated by loading hashHist
import history from './hashHist'
import AppRoutes from './AppRoutes'
console.log('start renderer.js loaded within index.html')
console.log('AppConfig.isElectron', AppConfig.isElectron)
console.log('HISTORY LOCATION', history.location)

let MyRouter = (AppConfig.isElectron === true) ? HashRouter : Router

// Error: Can't resolve 'fs'
/*
var tab = require('ya-csv')
var reader = tab.createCsvFileReader('./app-routes.txt', {
  'separator': '\t'
})
var data = []
reader.on('data', (record) => {
  data.push(record)
}).on('end', () => {
  console.log('TSV DATA', data)
})
*/

// ### Router
// BrowserRouter for dynamic web contents
// HashRouter for static web contents
// ===> for electron
//      history.push('/memo') works on HashRouter, not on BrowserRouter.
/*
const Root = () => (
  <div>
    <HashRouter history={history}>
      <AppRoutes />
    </HashRouter>
  </div>
)
*/

ReactDOM.render(
  <div>
    <MyRouter history={history}>
      <AppRoutes />
    </MyRouter>
  </div>,
  document.getElementById('reactapp')
)
